on:
  workflow_dispatch:
  push:
    tags:
      - "V*.*"

name: Build Aquarius+ firmware
run-name: Aquarius+ firmware ${{ github.ref_name }} ${{ github.event.repository.pushed_at }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get all Git tags
        run: git fetch --tags -f
      - name: Installing dependencies
        run: |
          sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
          sudo apt-get update -y -qq
          sudo apt-get install dos2unix
      - name: ESP-IDF build
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.3.1
          target: esp32s3
          path: "System/esp32"
      - name: Build release
        run: |
          cd System/esp32; ./do_release.sh nobuild
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Firmware_${{ github.ref_name }}
          path: System/esp32/AquariusPlus-Firmware-*.zip
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          prerelease: true
          files: |
            System/esp32/AquariusPlus-Firmware-*.zip
            System/esp32/build/aquarius-plus.bin
