on:
  workflow_dispatch:
  push:
    tags:
      - "V*.*"

name: Build Aquarius+ emulator for Windows
run-name: Aquarius+ emulator for Windows ${{ github.ref_name }} ${{ github.event.repository.pushed_at }}

jobs:
  build-windows:
    name: Build Windows emulator
    runs-on: windows-latest
    steps:
      - name: Checking out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - name: Get all Git tags
        run: git fetch --tags -f
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
      - name: Build app for release
        run: |
          $VERSION=git describe
          echo "const char *versionStr = ""$VERSION"";" > System\emulator\Version.cpp
          cmake -S System\emulator -B System\emulator\build
          msbuild System\emulator\build\aqplus-emu.sln -t:rebuild -p:Configuration=Release
      - name: Creating release directory structure for portable version
        run: |
          $VERSION=git describe
          mkdir System\emulator\build\Release\AquariusPlusEmu
          copy System\emulator\build\Release\aqplus-emu.exe System\emulator\build\Release\AquariusPlusEmu\
          copy System\emulator\windows\SDL2-2.0.20\lib\x64\SDL2.dll System\emulator\build\Release\AquariusPlusEmu\
          xcopy /E /I EndUser\sdcard System\emulator\build\Release\AquariusPlusEmu\sdcard
          cd System\emulator\build\Release
          Compress-Archive -Path AquariusPlusEmu -Destination AquariusPlusEmu-Windows-x64-portable-$VERSION.zip
      - name: Creating Inno Setup installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.5
        with:
          path: System/emulator/windows/AquariusPlusEmu.iss
      - name: Rename installer
        run: |
          $VERSION=git describe
          move System/emulator/windows/Output/AquariusPlusEmu-Windows-x64.exe System/emulator/windows/Output/AquariusPlusEmu-Windows-x64-installer-$VERSION.exe
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AquariusPlusEmu-Windows-x64-${{ github.ref_name }}
          path: |
            System/emulator/build/Release/AquariusPlusEmu-Windows-x64-portable-*.zip
            System/emulator/windows/Output/AquariusPlusEmu-Windows-x64-installer-*.exe
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          prerelease: true
          files: |
            System/emulator/build/Release/AquariusPlusEmu-Windows-x64-portable-*.zip
            System/emulator/windows/Output/AquariusPlusEmu-Windows-x64-installer-*.exe
