on:
  workflow_dispatch:
  push:
    tags:
      - "V*.*"

name: Build Aquarius+ emulator for Linux
run-name: Aquarius+ emulator for Linux ${{ github.ref_name }} ${{ github.event.repository.pushed_at }}

jobs:
  build-linux:
    name: Build Linux emulator
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - name: Get all Git tags
        run: git fetch --tags -f
      - name: Installing dependencies
        run: |
          sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
          sudo apt-get update -y -qq
          sudo apt-get install libsdl2-dev cmake ninja-build
      - name: Building Linux emulator
        run: |
          echo "const char *versionStr = \"`git describe`\";" > System/emulator/Version.cpp
          cmake -DCMAKE_BUILD_TYPE=Release -S System/emulator -B System/emulator/build -G Ninja
          ninja -C System/emulator/build
      - name: Creating release directory structure
        run: |
          cd System/emulator/build
          mkdir AquariusPlusEmu
          cp aqplus-emu AquariusPlusEmu/
          cp -r ../../../EndUser/sdcard AquariusPlusEmu/
          zip -rq AquariusPlusEmu-Linux-`git describe`.zip AquariusPlusEmu
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AquariusPlusEmu-Linux-${{ github.ref_name }}
          path: System/emulator/build/AquariusPlusEmu-Linux-*.zip
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          prerelease: true
          files: System/emulator/build/AquariusPlusEmu-Linux-*.zip
