on:
  workflow_dispatch:
  push:
    tags:
      - "V*.*"
    # paths:
    #   - System/emulator/**

name: Build Aquarius+ emulator
run-name: Aquarius+ emulator ${{ github.ref_name }} ${{ github.event.repository.pushed_at }}

jobs:
  build-macos:
    name: Build macOS emulator
    runs-on: macos-latest
    steps:
      - name: Checking out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get all Git tags
        run: git fetch --tags -f
      - name: Building macOS emulator
        run: |
          echo "const char *versionStr = \"`git describe`\";" > System/emulator/Version.cpp
          make -C System/emulator
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AquariusPlusEmu-macOS-${{ github.ref_name }}
          path: System/emulator/build/AquariusPlusEmu-macOS-*.zip
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          prerelease: true
          files: System/emulator/build/AquariusPlusEmu-macOS-*.zip

  build-linux:
    name: Build Linux emulator
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get all Git tags
        run: git fetch --tags -f
      - name: Installing dependencies
        run: |
          sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
          sudo apt-get update -y -qq
          sudo apt-get install libsdl2-dev
      - name: Building Linux emulator
        run: |
          echo "const char *versionStr = \"`git describe`\";" > System/emulator/Version.cpp
          make -C System/emulator
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AquariusPlusEmu-Linux-${{ github.ref_name }}
          path: System/emulator/build/AquariusPlusEmu-Linux-*.zip
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          prerelease: true
          files: System/emulator/build/AquariusPlusEmu-Linux-*.zip

  build-windows:
    name: Build Windows emulator
    runs-on: windows-latest
    steps:
      - name: Checking out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get all Git tags
        run: git fetch --tags -f
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
      - name: Build app for release
        run: |
          $VERSION=git describe
          echo "const char *versionStr = ""$VERSION"";" > System\emulator\Version.cpp
          msbuild System\emulator\windows\aquarius-emu.sln -t:rebuild -p:Configuration=Release
      - name: Creating release directory structure
        run: |
          $VERSION=git describe
          mkdir System\emulator\windows\x64\Release\AquariusPlusEmu
          copy System\emulator\windows\x64\Release\aquarius-emu.exe System\emulator\windows\x64\Release\AquariusPlusEmu\
          copy System\emulator\windows\SDL2-2.0.20\lib\x64\SDL2.dll System\emulator\windows\x64\Release\AquariusPlusEmu\
          xcopy /E /I EndUser\sdcard System\emulator\windows\x64\Release\AquariusPlusEmu\sdcard
          cd System\emulator\windows\x64\Release
          Compress-Archive -Path AquariusPlusEmu -Destination AquariusPlusEmu-Windows-x64-portable-$VERSION.zip
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AquariusPlusEmu-Windows-x64-${{ github.ref_name }}
          path: |
            System/emulator/windows/Installer/Release/AquariusPlusEmu*.msi
            System/emulator/windows/x64/Release/AquariusPlusEmu-Windows-x64-portable-*.zip
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          prerelease: true
          files: |
            System/emulator/windows/Installer/Release/AquariusPlusEmu*.msi
            System/emulator/windows/x64/Release/AquariusPlusEmu-Windows-x64-portable-*.zip

  build-sdcard:
    name: Build SD card ZIP
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get all Git tags
        run: git fetch --tags -f
      - name: Installing dependencies
        run: |
          sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
          sudo apt-get update -y -qq
          sudo apt-get install zip
      - name: Building ZIP files
        run: |
          cd EndUser
          mv sdcard AquariusPlusDisk
          zip -r AquariusPlusDisk-`git describe`.zip AquariusPlusDisk
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AquariusPlusDisk-${{ github.ref_name }}
          path: EndUser/AquariusPlusDisk-*.zip
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          prerelease: true
          files: EndUser/AquariusPlusDisk-*.zip
